2020-09-27 14:23:53,224 - ERROR - get_sysinfo: Traceback (most recent call last):
  File "E:\python_test\20200812\collector\lib\plugins\get_sysinfo.py", line 32, in linux
    self._parse_data(response.data)
TypeError: _parse_data() missing 1 required positional argument: 'data'

2020-09-27 14:23:53,325 - ERROR - get_sysinfo: Traceback (most recent call last):
  File "E:\python_test\20200812\collector\lib\plugins\get_sysinfo.py", line 32, in linux
    self._parse_data(response.data)
TypeError: _parse_data() missing 1 required positional argument: 'data'

2020-09-27 14:23:53,369 - ERROR - get_sysinfo: Traceback (most recent call last):
  File "E:\python_test\20200812\collector\lib\plugins\get_sysinfo.py", line 32, in linux
    self._parse_data(response.data)
TypeError: _parse_data() missing 1 required positional argument: 'data'

2020-09-27 14:23:53,380 - ERROR - get_sysinfo: Traceback (most recent call last):
  File "E:\python_test\20200812\collector\lib\plugins\get_sysinfo.py", line 32, in linux
    self._parse_data(response.data)
TypeError: _parse_data() missing 1 required positional argument: 'data'

2020-09-27 14:23:53,406 - ERROR - get_sysinfo: Traceback (most recent call last):
  File "E:\python_test\20200812\collector\lib\plugins\get_sysinfo.py", line 32, in linux
    self._parse_data(response.data)
TypeError: _parse_data() missing 1 required positional argument: 'data'

2020-09-27 14:23:53,740 - ERROR - get_sysinfo: Traceback (most recent call last):
  File "E:\python_test\20200812\collector\lib\plugins\get_sysinfo.py", line 32, in linux
    self._parse_data(response.data)
TypeError: _parse_data() missing 1 required positional argument: 'data'

2020-09-27 14:24:16,084 - ERROR - get_sysinfo: Traceback (most recent call last):
  File "E:\python_test\20200812\collector\lib\plugins\get_sysinfo.py", line 32, in linux
    self._parse_data(tgt, response.data)
  File "E:\python_test\20200812\collector\lib\plugins\get_sysinfo.py", line 44, in _parse_data
    virtual = data["virtual"]
KeyError: 'virtual'

2020-09-27 14:24:16,156 - ERROR - get_sysinfo: Traceback (most recent call last):
  File "E:\python_test\20200812\collector\lib\plugins\get_sysinfo.py", line 32, in linux
    self._parse_data(tgt, response.data)
  File "E:\python_test\20200812\collector\lib\plugins\get_sysinfo.py", line 44, in _parse_data
    virtual = data["virtual"]
KeyError: 'virtual'

2020-09-27 14:24:16,161 - ERROR - get_sysinfo: Traceback (most recent call last):
  File "E:\python_test\20200812\collector\lib\plugins\get_sysinfo.py", line 32, in linux
    self._parse_data(tgt, response.data)
  File "E:\python_test\20200812\collector\lib\plugins\get_sysinfo.py", line 44, in _parse_data
    virtual = data["virtual"]
KeyError: 'virtual'

2020-09-27 14:24:16,188 - ERROR - get_sysinfo: Traceback (most recent call last):
  File "E:\python_test\20200812\collector\lib\plugins\get_sysinfo.py", line 32, in linux
    self._parse_data(tgt, response.data)
  File "E:\python_test\20200812\collector\lib\plugins\get_sysinfo.py", line 44, in _parse_data
    virtual = data["virtual"]
KeyError: 'virtual'

2020-09-27 14:24:16,243 - ERROR - get_sysinfo: Traceback (most recent call last):
  File "E:\python_test\20200812\collector\lib\plugins\get_sysinfo.py", line 32, in linux
    self._parse_data(tgt, response.data)
  File "E:\python_test\20200812\collector\lib\plugins\get_sysinfo.py", line 44, in _parse_data
    virtual = data["virtual"]
KeyError: 'virtual'

2020-09-27 14:24:16,616 - ERROR - get_sysinfo: Traceback (most recent call last):
  File "E:\python_test\20200812\collector\lib\plugins\get_sysinfo.py", line 32, in linux
    self._parse_data(tgt, response.data)
  File "E:\python_test\20200812\collector\lib\plugins\get_sysinfo.py", line 44, in _parse_data
    virtual = data["virtual"]
KeyError: 'virtual'

2020-10-14 10:50:44,310 - ERROR - get_sysinfo: Traceback (most recent call last):
  File "E:\python_test\20200812\collector\lib\plugins\get_sysinfo.py", line 32, in linux
    response.data =  self._parse_data(tgt, result)
  File "E:\python_test\20200812\collector\lib\plugins\get_sysinfo.py", line 44, in _parse_data
    for key, value in data[tgt]["sysinfo"].items():
AttributeError: 'str' object has no attribute 'items'

2020-10-14 10:50:44,738 - ERROR - get_sysinfo: Traceback (most recent call last):
  File "E:\python_test\20200812\collector\lib\plugins\get_sysinfo.py", line 32, in linux
    response.data =  self._parse_data(tgt, result)
  File "E:\python_test\20200812\collector\lib\plugins\get_sysinfo.py", line 44, in _parse_data
    for key, value in data[tgt]["sysinfo"].items():
AttributeError: 'str' object has no attribute 'items'

2020-10-14 10:51:44,177 - ERROR - get_sysinfo: Traceback (most recent call last):
  File "E:\python_test\20200812\collector\lib\plugins\get_sysinfo.py", line 32, in linux
    response.data =  self._parse_data(tgt, result)
  File "E:\python_test\20200812\collector\lib\plugins\get_sysinfo.py", line 44, in _parse_data
    for key, value in data[tgt]["sysinfo"].items():
AttributeError: 'str' object has no attribute 'items'

2020-10-14 10:51:44,268 - ERROR - get_sysinfo: Traceback (most recent call last):
  File "E:\python_test\20200812\collector\lib\plugins\get_sysinfo.py", line 32, in linux
    response.data =  self._parse_data(tgt, result)
  File "E:\python_test\20200812\collector\lib\plugins\get_sysinfo.py", line 44, in _parse_data
    for key, value in data[tgt]["sysinfo"].items():
AttributeError: 'str' object has no attribute 'items'

2020-10-14 10:52:28,226 - ERROR - get_sysinfo: Traceback (most recent call last):
  File "E:\python_test\20200812\collector\lib\plugins\get_sysinfo.py", line 32, in linux
    response.data =  self._parse_data(tgt, result)
  File "E:\python_test\20200812\collector\lib\plugins\get_sysinfo.py", line 45, in _parse_data
    for key, value in data[tgt]["sysinfo"].items():
AttributeError: 'str' object has no attribute 'items'

2020-10-14 10:52:28,346 - ERROR - get_sysinfo: Traceback (most recent call last):
  File "E:\python_test\20200812\collector\lib\plugins\get_sysinfo.py", line 32, in linux
    response.data =  self._parse_data(tgt, result)
  File "E:\python_test\20200812\collector\lib\plugins\get_sysinfo.py", line 45, in _parse_data
    for key, value in data[tgt]["sysinfo"].items():
AttributeError: 'str' object has no attribute 'items'

